//
// Created by Данил Подлягин on 03.10.2024.
//

#ifndef INSURANCECOMPANYEMULATORTRUE_MAINWINDOW_H
#define INSURANCECOMPANYEMULATORTRUE_MAINWINDOW_H


class MainWindow {

};


#endif //INSURANCECOMPANYEMULATORTRUE_MAINWINDOW_H
